server:
  port: 8181
  #nacos服务名称
spring:
  application:
    name: order-nacos
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
logging:
  level:
    com.shieh.order.feign: debug
feign:
  client:
    config:
      product-service:
        loggerLevel: BASIC
        # 连接超时时间
        connectTimeout: 5000
        # 请求处理超时时间
        readTimeout: 5000

stock-nacos:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule