server:
  port: 8180
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: dev
    gateway:
      routes:
          - id: order_route # 路由的唯一标识
            uri: lb://order-nacos # 需要转发的地址
            # 配置断言规则，用于路由规则的匹配
            predicates:
            - Path=/order-service/**
            filters:
            - StripPrefix=1
